### ISSUE TITLE
Boot BIOS Twice Segfaults

### ISSUE THREAD

**Issue by CanadianJeff** [mgba-emu/mgba#164]
Load BIOS
Boot BIOS
Click BIOS Again
Segfault
```
jefferyw@xubuntu:~/.retro/roms/gameboyadvance$ gdb mgba-qt
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from mgba-qt...Reading symbols from /usr/lib/debug/.build-id/98/579b05d067512651e7ddc214d7ccc7bd148d0a.debug...done.
done.
(gdb) r
Starting program: /usr/games/mgba-qt 
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe0557700 (LWP 2837)]
[New Thread 0x7fffd3679700 (LWP 2838)]
[New Thread 0x7fffd2077700 (LWP 2839)]
[New Thread 0x7fffd1876700 (LWP 2840)]
[New Thread 0x7fffb633f700 (LWP 2841)]
[New Thread 0x7fffb5b3e700 (LWP 2842)]
[New Thread 0x7fffb533d700 (LWP 2843)]
[New Thread 0x7fffb4b3c700 (LWP 2844)]
[New Thread 0x7fffa7fff700 (LWP 2845)]
[New Thread 0x7fffa77fe700 (LWP 2846)]
[New Thread 0x7fffa6ffd700 (LWP 2847)]
[New Thread 0x7fffa67fc700 (LWP 2848)]
[Thread 0x7fffa7fff700 (LWP 2845) exited]
[Thread 0x7fffa67fc700 (LWP 2848) exited]
[Thread 0x7fffb5b3e700 (LWP 2842) exited]
[Thread 0x7fffa77fe700 (LWP 2846) exited]
[Thread 0x7fffa6ffd700 (LWP 2847) exited]
[Thread 0x7fffb533d700 (LWP 2843) exited]
[Thread 0x7fffb4b3c700 (LWP 2844) exited]
[New Thread 0x7fffb4b3c700 (LWP 2849)]
[New Thread 0x7fffb533d700 (LWP 2850)]
[New Thread 0x7fffa6ffd700 (LWP 2851)]
[Thread 0x7fffb533d700 (LWP 2850) exited]
[New Thread 0x7fffb533d700 (LWP 2852)]
QWidget::repaint: It is dangerous to leave painters active on a widget outside of the PaintEvent
[Thread 0x7fffb633f700 (LWP 2841) exited]
[Thread 0x7fffb4b3c700 (LWP 2849) exited]
[New Thread 0x7fffb4b3c700 (LWP 2853)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb4b3c700 (LWP 2853)]
__memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:36
36	../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: No such file or directory.
(gdb) bt full
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:36
No locals.
#1  0x00007ffff786b61f in memcpy (__len=<optimized out>, __src=<optimized out>, __dest=<optimized out>)
    at /usr/include/x86_64-linux-gnu/bits/string3.h:51
No locals.
#2  GBAMemoryReset (gba=gba@entry=0x7fffb4b3a850) at /build/mgba-bzOldK/mgba-0.4~WIP/src/gba/memory.c:101
        i = <optimized out>
#3  0x00007ffff785daab in GBAReset (cpu=<optimized out>) at /build/mgba-bzOldK/mgba-0.4~WIP/src/gba/gba.c:173
        gba = 0x7fffb4b3a850
#4  0x00007ffff788ca0a in _GBAThreadRun (context=0xa2fd50) at /build/mgba-bzOldK/mgba-0.4~WIP/src/gba/supervisor/thread.c:224
        gba = {d = {id = 16777216, init = 0x7ffff785d620 <GBAInit>, deinit = 0x0}, cpu = 0x7fffb4b3a640, memory = {
            bios = 0x7ffff789b0e0 <hleBios>, wram = 0x7fffd24ef000, iwram = 0x0, rom = 0x0, io = {128, 0, 0, 19, 
              0 <repeats 12 times>, 256, 0, 0, 256, 0, 0, 0, 0, 256, 0, 0, 256, 0 <repeats 40 times>, 512, 
              0 <repeats 83 times>, 1023, 0, 32768, 0 <repeats 357 times>}, hw = {p = 0x7fffb4b3a850, devices = 0, 
              readWrite = GPIO_WRITE_ONLY, gpioBase = 0x0, pinState = 0, direction = 0, rtc = {bytesRemaining = 0, 
                transferStep = 0, bitsRead = 0, bits = 0, commandActive = 0, command = 0, control = 0, 
                time = "\000\000\000\000\000\000"}, gyroSample = 0, gyroEdge = false, lightCounter = 0, lightSample = 0 '\000', 
              lightEdge = false, tiltX = 0, tiltY = 0, tiltState = 0, gbpInputsPosted = 0, gbpTxPosition = 0, gbpNextEvent = 0, 
              gbpCallback = {d = {readKeys = 0x0}, p = 0x0}, gbpDriver = {d = {p = 0x0, init = 0x0, deinit = 0x0, load = 0x0, 
                  unload = 0x0, writeRegister = 0x0, processEvents = 0x0}, p = 0x0}}, savedata = {type = SAVEDATA_AUTODETECT, 
              data = 0x0, command = EEPROM_COMMAND_NULL, vf = 0x0, mapMode = 2, realVf = 0x0, readBitsRemaining = 0, 
              readAddress = 0, writeAddress = 0, currentBank = 0x0, realisticTiming = false, settling = 0, dust = 0, 
              dirty = (unknown: 0), dirtAge = 0, flashState = FLASH_STATE_RAW}, romSize = 140735877748608, romMask = 0, 
            romID = 0, fullBios = 0, 
            waitstatesSeq32 = "\000\000\005\000\000\001\001\000\005\005\t\t\021\021\t", '\000' <repeats 240 times>, 
            waitstatesSeq16 = "\000\000\002\000\000\000\000\000\002\002\004\004\b\b\004", '\000' <repeats 240 times>, 
            waitstatesNonseq32 = "\000\000\005\000\000\001\001\000\a\a\t\t\r\r\t", '\000' <repeats 240 times>, 
            waitstatesNonseq16 = "\000\000\002\000\000\000\000\000\004\004\004\004\004\004\004", '\000' <repeats 240 times>, 
            waitstatesPrefetchSeq32 = "\000\000\005\000\000\001\001\000\005\005\t\t\021\021\t", 
            waitstatesPrefetchSeq16 = "\000\000\002\000\000\000\000\000\002\002\004\004\b\b\004", 
            waitstatesPrefetchNonseq32 = "\000\000\005\000\000\001\001\000\a\a\t\t\r\r\t", 
            waitstatesPrefetchNonseq16 = "\000\000\002\000\000\000\000\000\004\004\004\004\004\004\004", activeRegion = 0, 
            prefetch = false, lastPrefetchedPc = 0, lastPrefetchedLoads = 0, biosPrefetch = 0, dma = {{reg = 0, source = 0, 
                dest = 0, count = 16384, nextSource = 0, nextDest = 0, nextCount = 0, nextEvent = 2147483647}, {reg = 0, 
                source = 0, dest = 0, count = 16384, nextSource = 0, nextDest = 0, nextCount = 0, nextEvent = 2147483647}, {
                reg = 0, source = 0, dest = 0, count = 16384, nextSource = 0, nextDest = 0, nextCount = 0, 
                nextEvent = 2147483647}, {reg = 0, source = 0, dest = 0, count = 65536, nextSource = 0, nextDest = 0, 
                nextCount = 0, nextEvent = 2147483647}}, activeDMA = -1, nextDMA = 2147483647, eventDiff = 0}, video = {
            p = 0x7fffb4b3a850, renderer = 0xbc7bd0, vcount = 19, nextHblank = 1006, nextEvent = 190, eventDiff = 816, 
---Type <return> to continue, or q <return> to quit---
            nextHblankIRQ = 1006, nextVblankIRQ = 281902, nextVcounterIRQ = -198461648, palette = {0 <repeats 138 times>, 
              46441, 61377, 32767, 0, 0, 0, 0, 0, 49728, 50183, 32767, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 46448, 46259, 
              32767, 0, 0, 0, 0, 0, 55729, 61382, 32767, 0, 47328, 46259, 32767, 0, 18462, 61425, 32767, 0, 0, 0, 0, 0, 50944, 
              50183, 32767, 0, 0, 0, 0, 0, 1, 0, 0, 0, 46472, 46259, 32767, 0, 46441, 61377, 1599, 0, 49728, 50183, 32767, 0, 
              50320, 50183, 32767, 0, 1, 0, 32767, 0, 1, 0, 0, 0, 0, 0, 0, 0, 46576, 46259, 32767, 0, 0, 0, 0, 0, 55729, 61382, 
              32767, 0, 47456, 46259, 32767, 0, 18462, 61425, 32767, 0, 50944, 50183, 32767, 0, 0, 0, 0, 0, 1, 0, 0, 0, 32, 0, 
              0, 0, 19121, 19276, 32768, 65535, 3, 0, 1599, 0, 0, 0, 0, 0, 48, 0, 0, 0, 1, 0, 32767, 0, 0, 0, 0, 0, 0, 0, 91, 
              0, 0, 0, 0, 0, 0, 0, 0, 0, 110, 0, 119, 0, 0, 0, 0, 0, 46415, 46259, 32767, 0, 0, 0, 0, 0, 44544, 25061, 53869, 
              592, 19009, 19276, 32768, 65535, 46752, 46259, 32767, 0, 49728, 50183...}, vram = 0x0, oam = {obj = {{a = 512, 
                  b = 0, c = 0, d = 0} <repeats 128 times>}, mat = {{padding0 = {512, 0, 0}, a = 0, padding1 = {512, 0, 0}, 
                  b = 0, padding2 = {512, 0, 0}, c = 0, padding3 = {512, 0, 0}, d = 0} <repeats 32 times>}, raw = {512, 0, 0, 
                0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 
                0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 
                0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 
                0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 
                0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 
                0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 0, 512, 0, 0, 
                0, 512, 0, 0, 0...}}, frameCounter = 707, frameskip = 0, frameskipCounter = 0}, audio = {p = 0x7fffb4b3a850, 
            ch1 = {sweep = {shift = 0 '\000', time = 0 '\000', direction = false}, nextSweep = 2147483647, envelope = {
                length = 0 '\000', duty = 0 '\000', stepTime = 0 '\000', initialVolume = 0 '\000', direction = false, 
                currentVolume = 0, dead = 0, nextStep = 2147483647}, control = {frequency = 0, stop = false, hi = 0, 
                nextStep = 0, endTime = 0}, sample = 0 '\000'}, ch2 = {envelope = {length = 0 '\000', duty = 0 '\000', 
                stepTime = 0 '\000', initialVolume = 0 '\000', direction = false, currentVolume = 0, dead = 0, 
                nextStep = 2147483647}, control = {frequency = 0, stop = false, hi = 0, nextStep = 0, endTime = 0}, 
              sample = 0 '\000'}, ch3 = {bank = {size = false, bank = false, enable = false}, wave = {length = 0 '\000', 
                volume = 0 '\000'}, control = {rate = 0, stop = false, endTime = 0}, wavedata = {0, 0, 0, 0, 0, 0, 0, 0}, 
              sample = 0 '\000'}, ch4 = {envelope = {length = 0 '\000', duty = 0 '\000', stepTime = 0 '\000', 
                initialVolume = 0 '\000', direction = false, currentVolume = 0, dead = 0, nextStep = 2147483647}, control = {
                ratio = 0 '\000', frequency = 0 '\000', power = false, stop = false, endTime = 0}, lfsr = 0, 
              sample = 0 '\000'}, chA = {fifo = {data = 0x7fffa00016e0, capacity = 32, size = 0, readPtr = 0x7fffa00016e0, 
                writePtr = 0x7fffa00016e0}, dmaSource = 1, sample = 0 '\000'}, chB = {fifo = {data = 0x7fffa00014b0, 
                capacity = 32, size = 0, readPtr = 0x7fffa00014b0, writePtr = 0x7fffa00014b0}, dmaSource = 2, 
              sample = 0 '\000'}, left = 0x7fffa00019c0, right = 0x7fffa0011a30, lastLeft = 0, lastRight = 0, clock = 0, 
            volumeRight = 0 '\000', volumeLeft = 0 '\000', ch1Right = false, ch2Right = false, ch3Right = false, 
            ch4Right = false, ch1Left = false, ch2Left = false, ch3Left = false, ch4Left = false, volume = 0 '\000', 
            volumeChA = false, volumeChB = false, chARight = false, chALeft = false, chATimer = false, chBRight = false, 
            chBLeft = false, chBTimer = false, playingCh1 = false, playingCh2 = false, playingCh3 = false, playingCh4 = false, 
            enable = false, samples = 1536, sampleRate = 32768, soundbias = 512, nextEvent = 512, eventDiff = 0, nextCh1 = 0, 
            nextCh2 = 0, nextCh3 = 0, nextCh4 = 0, nextSample = 512, sampleInterval = 512, forceDisableCh = {false, false, 
---Type <return> to continue, or q <return> to quit---
              false, false}, forceDisableChA = false, forceDisableChB = false, masterVolume = 256}, sio = {p = 0x7fffb4b3a850, 
            mode = SIO_GPIO, drivers = {normal = 0x0, multiplayer = 0x0, joybus = 0x0}, activeDriver = 0x0, rcnt = 32768, {
              normalControl = {sc = 0, internalSc = 0, si = 0, idleSo = 0, start = 0, length = 0, irq = 0}, 
              multiplayerControl = {baud = 0, slave = 0, ready = 0, id = 0, error = 0, busy = 0, irq = 0}, siocnt = 0}}, 
          sync = 0xa2fed8, debugger = 0x0, bus = 2684360817, performingDMA = 0, timersEnabled = 0, timers = {{reload = 0, 
              oldReload = 0, lastEvent = 0, nextEvent = 0, overflowInterval = 0, flags = 0}, {reload = 0, oldReload = 0, 
              lastEvent = 0, nextEvent = 0, overflowInterval = 0, flags = 0}, {reload = 0, oldReload = 0, lastEvent = 0, 
              nextEvent = 0, overflowInterval = 0, flags = 0}, {reload = 0, oldReload = 0, lastEvent = 0, nextEvent = 0, 
              overflowInterval = 0, flags = 0}}, springIRQ = 0, biosChecksum = 1494114645, keySource = 0x0, 
          rotationSource = 0x0, luminanceSource = 0x0, rtcSource = 0x0, rumble = 0x0, rr = 0x0, pristineRom = 0x7fffa0001800, 
          pristineRomSize = 140735877748849, yankedRomSize = 0, romCrc32 = 0, romVf = 0x0, biosVf = 0x0, 
          activeFile = 0x7ffff5ab25cf <QThread::~QThread()+127> "H\203\304 []A\\A]A^\303\017\037@", logHandler = 0x453750
     <QGBA::GameController::GameController(QObject*)::{lambda(GBAThread*, GBALogLevel, char const*, __va_list_tag*)#7}::_FUN(GBAThread*, GBALogLevel, char const*, __va_list_tag*)>, logLevel = GBA_LOG_ALL, stream = 0x0, keyCallback = 0x0, 
          stopCallback = 0x7fffb4b3a550, idleOptimization = IDLE_LOOP_REMOVE, idleLoop = 4294967295, lastJump = 0, 
          haltPending = 255, idleDetectionStep = -1610607648, idleDetectionFailures = 32767, cachedRegisters = {-223149272, 
            32767, -1580312925, 1231755747, 128, 0, -225311984, 32767, -223149176, 32767, 0, 0, -223149272, 32767, -1263285640, 
            32767}, taintedRegisters = {136, 3, 179, 242, 255, 127, false, false, false, false, false, false, false, false, 
            false, false}, realisticTiming = true, hardCrash = true}
        cpu = {gprs = {0 <repeats 13 times>, 50364160, 0, 4}, cpsr = {{priv = MODE_SYSTEM, t = MODE_ARM, f = 0, i = 0, v = 0, 
              c = 0, z = 0, n = 0}, packed = 31}, spsr = {{priv = 0, t = MODE_ARM, f = 0, i = 0, v = 0, c = 0, z = 0, n = 0}, 
            packed = 0}, cycles = 0, nextEvent = 0, halted = 0, bankedRegisters = {{0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 
              0}, {50364320, 0, 0, 0, 0, 0, 0}, {50364384, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0}}, 
          bankedSPSRs = {0, 0, 0, 0, 0, 0}, shifterOperand = 0, shifterCarryOut = 0, prefetch = {3925868550, 3942645758}, 
          executionMode = MODE_ARM, privilegeMode = MODE_SYSTEM, memory = {load32 = 0x7ffff7866e20 <GBALoad32>, 
            load16 = 0x7ffff78671c0 <GBALoad16>, load8 = 0x7ffff7866940 <GBALoad8>, store32 = 0x7ffff7867dc0 <GBAStore32>, 
            store16 = 0x7ffff7868090 <GBAStore16>, store8 = 0x7ffff7867b10 <GBAStore8>, 
            loadMultiple = 0x7ffff7868310 <GBALoadMultiple>, storeMultiple = 0x7ffff7869ad0 <GBAStoreMultiple>, 
            activeRegion = 0x7ffff789b0e0 <hleBios>, activeMask = 16383, activeSeqCycles32 = 0, activeSeqCycles16 = 0, 
            activeNonseqCycles32 = 0, activeNonseqCycles16 = 0, stall = 0x7ffff7866860 <GBAMemoryStall>, 
            setActiveRegion = 0x7ffff7867570 <GBASetActiveRegion>}, irqh = {reset = 0x7ffff785da10 <GBAReset>, 
            processEvents = 0x7ffff785e3f0 <GBAProcessEvents>, swi16 = 0x7ffff7865190 <GBASwi16>, 
            swi32 = 0x7ffff7866820 <GBASwi32>, hitIllegal = 0x7ffff785e350 <GBAIllegal>, 
            bkpt16 = 0x7ffff785d4e0 <GBABreakpoint>, bkpt32 = 0x7ffff785d4e0 <GBABreakpoint>, 
            readCPSR = 0x7ffff785d4a0 <GBATestIRQ>, hitStub = 0x7ffff785e2d0 <GBAHitStub>}, master = 0x7fffb4b3a850, 
          numComponents = 2, components = 0x7fffb4b3a540}
        patch = {vf = 0x0, outputSize = 0x0, applyPatch = 0x0}
        cheatDevice = {d = {id = 0, init = 0x0, deinit = 0x0}, p = 0x0, cheats = {vector = 0x0, size = 0, capacity = 0}}
        threadContext = 0xa2fd50
---Type <return> to continue, or q <return> to quit---
        components = {0x0, 0x0}
        movie = 0x0
        signals = {__val = {0 <repeats 16 times>}}
        stop = {d = {stop = 0x7ffff788c350 <_stopCallback>}, p = 0xa2fd50}
#5  0x00007ffff291f182 in start_thread (arg=0x7fffb4b3c700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7fffb4b3c700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736225068800, -5290479946306791773, 1, 19221792, 140736225069504, 
                140736225068800, 5290350652739704483, 5290486732835542691}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 
              0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#6  0x00007ffff4f3947d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.
```

**Comment by endrift** [comment]
Is this still broken? It should have been fixed by fe8c632c78eba9584354e79ab1c0a4008275e53a.
