### ISSUE TITLE
Error during installation of mgba.py

### ISSUE THREAD

**Issue by Jourdelune** [mgba-emu/mgba#2196]
Hello, I installed mgba (which works) by activating the use of python, I tried to import the mgba module but it does not exist, I also checked where my modules are stored, so I went to the folder ` /src/platform/python` and made: `python3 setup.py install`.
Unfortunately I get this error:

```pi@raspberrypi:~/build/src/platform/python $ python3 setup.py install --user
running install
running bdist_egg
running egg_info
writing mgba.egg-info/PKG-INFO
writing dependency_links to mgba.egg-info/dependency_links.txt
writing requirements to mgba.egg-info/requires.txt
writing top-level names to mgba.egg-info/top_level.txt
reading manifest file 'mgba.egg-info/SOURCES.txt'
writing manifest file 'mgba.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-aarch64/egg
running install_lib
running build_py
running build_ext
generating cffi module 'build/temp.linux-aarch64-3.7/mgba._pylib.c'
already up-to-date
building 'mgba._pylib' extension
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/pi/build/src/platform/python/../../../include -I/home/pi/build/src/platform/python/../.. -I/usr/include/python3.7m -c build/temp.linux-aarch64-3.7/mgba._pylib.c -o build/temp.linux-aarch64-3.7/build/temp.linux-aarch64-3.7/mgba._pylib.o -I/home/pi/build/src/platform/python/../../../include -I/home/pi/build/src/platform/python/../.. -I/home/pi/build/src/platform/python/..
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/pi/build/src/platform/python/../../../include -I/home/pi/build/src/platform/python/../.. -I/usr/include/python3.7m -c /home/pi/build/src/platform/python/vfs-py.c -o build/temp.linux-aarch64-3.7/home/pi/build/src/platform/python/vfs-py.o -I/home/pi/build/src/platform/python/../../../include -I/home/pi/build/src/platform/python/../.. -I/home/pi/build/src/platform/python/..
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/pi/build/src/platform/python/../../../include -I/home/pi/build/src/platform/python/../.. -I/usr/include/python3.7m -c /home/pi/build/src/platform/python/core.c -o build/temp.linux-aarch64-3.7/home/pi/build/src/platform/python/core.o -I/home/pi/build/src/platform/python/../../../include -I/home/pi/build/src/platform/python/../.. -I/home/pi/build/src/platform/python/..
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/pi/build/src/platform/python/../../../include -I/home/pi/build/src/platform/python/../.. -I/usr/include/python3.7m -c /home/pi/build/src/platform/python/log.c -o build/temp.linux-aarch64-3.7/home/pi/build/src/platform/python/log.o -I/home/pi/build/src/platform/python/../../../include -I/home/pi/build/src/platform/python/../.. -I/home/pi/build/src/platform/python/..
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/pi/build/src/platform/python/../../../include -I/home/pi/build/src/platform/python/../.. -I/usr/include/python3.7m -c /home/pi/build/src/platform/python/sio.c -o build/temp.linux-aarch64-3.7/home/pi/build/src/platform/python/sio.o -I/home/pi/build/src/platform/python/../../../include -I/home/pi/build/src/platform/python/../.. -I/home/pi/build/src/platform/python/..
Traceback (most recent call last):
  File "setup.py", line 33, in <module>
    "Topic :: System :: Emulators"
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 24, in run
    self.build()
  File "/usr/lib/python3.7/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/pi/.local/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 144, in run
    base_class.run(self)
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 78, in run
    _build_ext.run(self)
  File "/home/pi/.local/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/pi/.local/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 199, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 559, in build_extension
    target_lang=language)
  File "/usr/lib/python3.7/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/usr/lib/python3.7/distutils/unixccompiler.py", line 170, in link
    libraries)
  File "/usr/lib/python3.7/distutils/ccompiler.py", line 1092, in gen_lib_options
    opt = compiler.runtime_library_dir_option(dir)
  File "/usr/lib/python3.7/distutils/unixccompiler.py", line 264, in runtime_library_dir_option
    return "-Wl,--enable-new-dtags,-R" + dir
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by endrift** [comment]
That won't work, you need to do `cmake . -DBUILD_PYTHON=ON` in your build directory.

**Comment by Jourdelune** [comment]
``` cmake . -DBUILD_PYTHON=ON
-- Checking for one of the modules 'libedit'
CMake Warning at src/platform/cmake/FindFeature.cmake:51 (message):
  Requested module libedit missing for feature USE_EDITLINE.  Feature
  disabled.
Call Stack (most recent call first):
  CMakeLists.txt:450 (find_feature)


-- Checking for one of the modules 'libavfilter'
CMake Warning at src/platform/cmake/FindFeature.cmake:51 (message):
  Requested module libavfilter missing for feature USE_FFMPEG.  Feature
  disabled.
Call Stack (most recent call first):
  CMakeLists.txt:514 (find_feature)


-- Checking for one of the modules 'minizip'
CMake Warning at src/platform/cmake/FindFeature.cmake:51 (message):
  Requested module minizip missing for feature USE_MINIZIP.  Feature
  disabled.
Call Stack (most recent call first):
  CMakeLists.txt:517 (find_feature)


-- Checking for one of the modules 'libzip'
CMake Warning at src/platform/cmake/FindFeature.cmake:51 (message):
  Requested module libzip missing for feature USE_LIBZIP.  Feature disabled.
Call Stack (most recent call first):
  CMakeLists.txt:519 (find_feature)


-- Checking for one of the modules 'libelf'
CMake Warning at src/platform/cmake/FindFeature.cmake:51 (message):
  Requested module libelf missing for feature USE_ELF.  Feature disabled.
Call Stack (most recent call first):
  CMakeLists.txt:523 (find_feature)


CMake Warning at src/platform/qt/CMakeLists.txt:25 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


CMake Warning at src/platform/qt/CMakeLists.txt:33 (message):
  Cannot find Qt modules


-- Build type: Release
-- Platforms:
-- 	Game Boy Advance: ON
-- 	Game Boy: ON
-- Features:
-- 	Debuggers: ON
-- 	CLI debugger: OFF
-- 	GDB stub: ON
-- 	GIF/Video recording: OFF
-- 	Screenshot/advanced savestate support: ON
-- 	ZIP support: minizip (included)
-- 	7-Zip support: ON
-- 	SQLite3 game database: OFF
-- 	ELF loading support: OFF
-- 	Discord Rich Presence support: ON
-- 	OpenGL support: libepoxy
-- Frontends:
-- 	Qt: ON
-- 	SDL (2): ON
-- 	Profiling: OFF
-- 	Test harness: OFF
-- 	Test suite: OFF
-- 	Video test suite: OFF
-- 	Python bindings: ON
-- 	Examples: OFF
-- Cores:
-- 	Libretro core: OFF
-- Libraries:
-- 	Static: OFF
-- 	Shared: ON
-- Configuring done
Warning: Source file "/home/pi/build/src/platform/python/lib.c" is listed multiple times for target "mgba-pylib".
-- Generating done
-- Build files have been written to: /home/pi/build```

**Comment by Jourdelune** [comment]
and make:
```make
[  0%] Built target mgba-version-info
[ 88%] Built target mgba
[ 88%] Built target README
[ 89%] Built target README_DE
[ 89%] Built target README_ES
[ 90%] Built target README_ZH_CN
[ 94%] Built target mgba-pylib
running build
running build_py
running build_ext
generating cffi module '/home/pi/build/python/temp.linux-aarch64-3.7/mgba._pylib.c'
already up-to-date
[ 94%] Built target mgba-py
[100%] Built target mgba-sdl``` and 
sudo make install ```
pi@raspberrypi:~/build $ sudo make install
[  0%] Built target mgba-version-info
[ 88%] Built target mgba
[ 88%] Built target README
[ 89%] Built target README_DE
[ 89%] Built target README_ES
[ 90%] Built target README_ZH_CN
[ 94%] Built target mgba-pylib
running build
running build_py
running build_ext
generating cffi module '/home/pi/build/python/temp.linux-aarch64-3.7/mgba._pylib.c'
already up-to-date
[ 94%] Built target mgba-py
[100%] Built target mgba-sdl
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/lib/arm-linux-gnueabihf/libmgba.so.0.9.1
-- Up-to-date: /usr/lib/arm-linux-gnueabihf/libmgba.so.0.9
-- Up-to-date: /usr/lib/arm-linux-gnueabihf/libmgba.so
-- Up-to-date: /usr/share/icons/hicolor/16x16/apps/mgba.png
-- Up-to-date: /usr/share/icons/hicolor/24x24/apps/mgba.png
-- Up-to-date: /usr/share/icons/hicolor/32x32/apps/mgba.png
-- Up-to-date: /usr/share/icons/hicolor/48x48/apps/mgba.png
-- Up-to-date: /usr/share/icons/hicolor/64x64/apps/mgba.png
-- Up-to-date: /usr/share/icons/hicolor/96x96/apps/mgba.png
-- Up-to-date: /usr/share/icons/hicolor/128x128/apps/mgba.png
-- Up-to-date: /usr/share/icons/hicolor/256x256/apps/mgba.png
-- Up-to-date: /usr/share/icons/hicolor/512x512/apps/mgba.png
-- Up-to-date: /usr/include/mgba
-- Up-to-date: /usr/include/mgba/debugger
-- Up-to-date: /usr/include/mgba/debugger/debugger.h
-- Up-to-date: /usr/include/mgba/core
-- Up-to-date: /usr/include/mgba/core/library.h
-- Up-to-date: /usr/include/mgba/core/serialize.h
-- Up-to-date: /usr/include/mgba/core/core.h
-- Up-to-date: /usr/include/mgba/core/directories.h
-- Up-to-date: /usr/include/mgba/core/cheats.h
-- Up-to-date: /usr/include/mgba/core/log.h
-- Up-to-date: /usr/include/mgba/core/bitmap-cache.h
-- Up-to-date: /usr/include/mgba/core/config.h
-- Up-to-date: /usr/include/mgba/core/lockstep.h
-- Up-to-date: /usr/include/mgba/core/tile-cache.h
-- Up-to-date: /usr/include/mgba/core/version.h
-- Up-to-date: /usr/include/mgba/core/thread.h
-- Up-to-date: /usr/include/mgba/core/map-cache.h
-- Up-to-date: /usr/include/mgba/core/timing.h
-- Up-to-date: /usr/include/mgba/core/input.h
-- Up-to-date: /usr/include/mgba/core/mem-search.h
-- Up-to-date: /usr/include/mgba/core/scripting.h
-- Up-to-date: /usr/include/mgba/core/cpu.h
-- Up-to-date: /usr/include/mgba/core/blip_buf.h
-- Up-to-date: /usr/include/mgba/core/cache-set.h
-- Up-to-date: /usr/include/mgba/core/rewind.h
-- Up-to-date: /usr/include/mgba/core/sync.h
-- Up-to-date: /usr/include/mgba/core/interface.h
-- Up-to-date: /usr/include/mgba/feature
-- Up-to-date: /usr/include/mgba/feature/video-logger.h
-- Up-to-date: /usr/include/mgba/feature/commandline.h
-- Up-to-date: /usr/include/mgba/feature/thread-proxy.h
-- Up-to-date: /usr/include/mgba/internal
-- Up-to-date: /usr/include/mgba/internal/debugger
-- Up-to-date: /usr/include/mgba/internal/debugger/symbols.h
-- Up-to-date: /usr/include/mgba/internal/debugger/gdb-stub.h
-- Up-to-date: /usr/include/mgba/internal/debugger/cli-debugger.h
-- Up-to-date: /usr/include/mgba/internal/debugger/stack-trace.h
-- Up-to-date: /usr/include/mgba/internal/debugger/parser.h
-- Up-to-date: /usr/include/mgba/internal/gba
-- Up-to-date: /usr/include/mgba/internal/gba/overrides.h
-- Up-to-date: /usr/include/mgba/internal/gba/extra
-- Up-to-date: /usr/include/mgba/internal/gba/extra/cli.h
-- Up-to-date: /usr/include/mgba/internal/gba/extra/audio-mixer.h
-- Up-to-date: /usr/include/mgba/internal/gba/serialize.h
-- Up-to-date: /usr/include/mgba/internal/gba/matrix.h
-- Up-to-date: /usr/include/mgba/internal/gba/cheats.h
-- Up-to-date: /usr/include/mgba/internal/gba/hardware.h
-- Up-to-date: /usr/include/mgba/internal/gba/savedata.h
-- Up-to-date: /usr/include/mgba/internal/gba/io.h
-- Up-to-date: /usr/include/mgba/internal/gba/audio.h
-- Up-to-date: /usr/include/mgba/internal/gba/video.h
-- Up-to-date: /usr/include/mgba/internal/gba/bios.h
-- Up-to-date: /usr/include/mgba/internal/gba/timer.h
-- Up-to-date: /usr/include/mgba/internal/gba/input.h
-- Up-to-date: /usr/include/mgba/internal/gba/sio
-- Up-to-date: /usr/include/mgba/internal/gba/sio/lockstep.h
-- Up-to-date: /usr/include/mgba/internal/gba/sio/dolphin.h
-- Up-to-date: /usr/include/mgba/internal/gba/sio.h
-- Up-to-date: /usr/include/mgba/internal/gba/memory.h
-- Up-to-date: /usr/include/mgba/internal/gba/sharkport.h
-- Up-to-date: /usr/include/mgba/internal/gba/renderers
-- Up-to-date: /usr/include/mgba/internal/gba/renderers/gl.h
-- Up-to-date: /usr/include/mgba/internal/gba/renderers/common.h
-- Up-to-date: /usr/include/mgba/internal/gba/renderers/video-software.h
-- Up-to-date: /usr/include/mgba/internal/gba/renderers/proxy.h
-- Up-to-date: /usr/include/mgba/internal/gba/renderers/cache-set.h
-- Up-to-date: /usr/include/mgba/internal/gba/vfame.h
-- Up-to-date: /usr/include/mgba/internal/gba/gba.h
-- Up-to-date: /usr/include/mgba/internal/gba/dma.h
-- Up-to-date: /usr/include/mgba/internal/gb
-- Up-to-date: /usr/include/mgba/internal/gb/overrides.h
-- Up-to-date: /usr/include/mgba/internal/gb/extra
-- Up-to-date: /usr/include/mgba/internal/gb/extra/cli.h
-- Up-to-date: /usr/include/mgba/internal/gb/serialize.h
-- Up-to-date: /usr/include/mgba/internal/gb/cheats.h
-- Up-to-date: /usr/include/mgba/internal/gb/debugger
-- Up-to-date: /usr/include/mgba/internal/gb/debugger/symbols.h
-- Up-to-date: /usr/include/mgba/internal/gb/debugger/debugger.h
-- Up-to-date: /usr/include/mgba/internal/gb/io.h
-- Up-to-date: /usr/include/mgba/internal/gb/audio.h
-- Up-to-date: /usr/include/mgba/internal/gb/video.h
-- Up-to-date: /usr/include/mgba/internal/gb/gb.h
-- Up-to-date: /usr/include/mgba/internal/gb/timer.h
-- Up-to-date: /usr/include/mgba/internal/gb/input.h
-- Up-to-date: /usr/include/mgba/internal/gb/sio
-- Up-to-date: /usr/include/mgba/internal/gb/sio/lockstep.h
-- Up-to-date: /usr/include/mgba/internal/gb/sio/printer.h
-- Up-to-date: /usr/include/mgba/internal/gb/sio.h
-- Up-to-date: /usr/include/mgba/internal/gb/memory.h
-- Up-to-date: /usr/include/mgba/internal/gb/mbc.h
-- Up-to-date: /usr/include/mgba/internal/gb/renderers
-- Up-to-date: /usr/include/mgba/internal/gb/renderers/software.h
-- Up-to-date: /usr/include/mgba/internal/gb/renderers/proxy.h
-- Up-to-date: /usr/include/mgba/internal/gb/renderers/cache-set.h
-- Up-to-date: /usr/include/mgba/internal/sm83
-- Up-to-date: /usr/include/mgba/internal/sm83/decoder.h
-- Up-to-date: /usr/include/mgba/internal/sm83/debugger
-- Up-to-date: /usr/include/mgba/internal/sm83/debugger/cli-debugger.h
-- Up-to-date: /usr/include/mgba/internal/sm83/debugger/debugger.h
-- Up-to-date: /usr/include/mgba/internal/sm83/debugger/memory-debugger.h
-- Up-to-date: /usr/include/mgba/internal/sm83/sm83.h
-- Up-to-date: /usr/include/mgba/internal/sm83/isa-sm83.h
-- Up-to-date: /usr/include/mgba/internal/sm83/emitter-sm83.h
-- Up-to-date: /usr/include/mgba/internal/arm
-- Up-to-date: /usr/include/mgba/internal/arm/decoder.h
-- Up-to-date: /usr/include/mgba/internal/arm/isa-thumb.h
-- Up-to-date: /usr/include/mgba/internal/arm/emitter-arm.h
-- Up-to-date: /usr/include/mgba/internal/arm/emitter-thumb.h
-- Up-to-date: /usr/include/mgba/internal/arm/debugger
-- Up-to-date: /usr/include/mgba/internal/arm/debugger/cli-debugger.h
-- Up-to-date: /usr/include/mgba/internal/arm/debugger/debugger.h
-- Up-to-date: /usr/include/mgba/internal/arm/debugger/memory-debugger.h
-- Up-to-date: /usr/include/mgba/internal/arm/arm.h
-- Up-to-date: /usr/include/mgba/internal/arm/isa-inlines.h
-- Up-to-date: /usr/include/mgba/internal/arm/decoder-inlines.h
-- Up-to-date: /usr/include/mgba/internal/arm/emitter-inlines.h
-- Up-to-date: /usr/include/mgba/internal/arm/isa-arm.h
-- Up-to-date: /usr/include/mgba/internal/arm/macros.h
-- Up-to-date: /usr/include/mgba/gba
-- Up-to-date: /usr/include/mgba/gba/core.h
-- Up-to-date: /usr/include/mgba/gba/interface.h
-- Up-to-date: /usr/include/mgba/flags.h
-- Up-to-date: /usr/include/mgba/gb
-- Up-to-date: /usr/include/mgba/gb/core.h
-- Up-to-date: /usr/include/mgba/gb/interface.h
-- Up-to-date: /usr/include/mgba-util
-- Up-to-date: /usr/include/mgba-util/png-io.h
-- Up-to-date: /usr/include/mgba-util/common.h
-- Up-to-date: /usr/include/mgba-util/ring-fifo.h
-- Up-to-date: /usr/include/mgba-util/dllexports.h
-- Up-to-date: /usr/include/mgba-util/hash.h
-- Up-to-date: /usr/include/mgba-util/gui
-- Up-to-date: /usr/include/mgba-util/gui/font-metrics.h
-- Up-to-date: /usr/include/mgba-util/gui/font.h
-- Up-to-date: /usr/include/mgba-util/gui/menu.h
-- Up-to-date: /usr/include/mgba-util/gui/file-select.h
-- Up-to-date: /usr/include/mgba-util/vfs.h
-- Up-to-date: /usr/include/mgba-util/table.h
-- Up-to-date: /usr/include/mgba-util/crc32.h
-- Up-to-date: /usr/include/mgba-util/string.h
-- Up-to-date: /usr/include/mgba-util/patch
-- Up-to-date: /usr/include/mgba-util/patch/ips.h
-- Up-to-date: /usr/include/mgba-util/patch/ups.h
-- Up-to-date: /usr/include/mgba-util/patch/fast.h
-- Up-to-date: /usr/include/mgba-util/gui.h
-- Up-to-date: /usr/include/mgba-util/text-codec.h
-- Up-to-date: /usr/include/mgba-util/formatting.h
-- Up-to-date: /usr/include/mgba-util/elf-read.h
-- Up-to-date: /usr/include/mgba-util/threading.h
-- Up-to-date: /usr/include/mgba-util/circle-buffer.h
-- Up-to-date: /usr/include/mgba-util/patch.h
-- Up-to-date: /usr/include/mgba-util/memory.h
-- Up-to-date: /usr/include/mgba-util/vector.h
-- Up-to-date: /usr/include/mgba-util/socket.h
-- Up-to-date: /usr/include/mgba-util/math.h
-- Up-to-date: /usr/include/mgba-util/platform
-- Up-to-date: /usr/include/mgba-util/platform/3ds
-- Up-to-date: /usr/include/mgba-util/platform/3ds/3ds-vfs.h
-- Up-to-date: /usr/include/mgba-util/platform/3ds/threading.h
-- Up-to-date: /usr/include/mgba-util/platform/psp2
-- Up-to-date: /usr/include/mgba-util/platform/psp2/sce-vfs.h
-- Up-to-date: /usr/include/mgba-util/platform/psp2/threading.h
-- Up-to-date: /usr/include/mgba-util/platform/posix
-- Up-to-date: /usr/include/mgba-util/platform/posix/threading.h
-- Up-to-date: /usr/include/mgba-util/platform/switch
-- Up-to-date: /usr/include/mgba-util/platform/switch/threading.h
-- Up-to-date: /usr/include/mgba-util/platform/windows
-- Up-to-date: /usr/include/mgba-util/platform/windows/getopt.h
-- Up-to-date: /usr/include/mgba-util/platform/windows/threading.h
-- Up-to-date: /usr/include/mgba-util/configuration.h
-- Up-to-date: /usr/include/mgba-util/export.h
-- Up-to-date: /usr/include/mgba/flags.h
-- Up-to-date: /usr/share/doc/mGBA/licenses/blip_buf.txt
-- Up-to-date: /usr/share/doc/mGBA/licenses/inih.txt
-- Up-to-date: /usr/share/doc/mGBA/licenses/discord-rpc.txt
-- Up-to-date: /usr/share/doc/mGBA/licenses/rapidjson.txt
-- Up-to-date: /usr/share/doc/mGBA/README.md
-- Up-to-date: /usr/share/doc/mGBA/README_DE.md
-- Up-to-date: /usr/share/doc/mGBA/README_ES.md
-- Up-to-date: /usr/share/doc/mGBA/README_ZH_CN.md
-- Up-to-date: /usr/share/doc/mGBA/CHANGES
-- Up-to-date: /usr/share/doc/mGBA/LICENSE
-- Up-to-date: /usr/share/doc/mGBA/README.html
-- Up-to-date: /usr/share/doc/mGBA/README_DE.html
-- Up-to-date: /usr/share/doc/mGBA/README_ES.html
-- Up-to-date: /usr/share/doc/mGBA/README_ZH_CN.html
-- Up-to-date: /usr/bin/mgba
-- Up-to-date: /usr/share/man/man6/mgba.6
```

**Comment by Jourdelune** [comment]
and I have module not found
```>>> import mgba
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'mgba'
>>> import .mgba
  File "<stdin>", line 1
    import .mgba
           ^
SyntaxError: invalid syntax
>>> import mgba.core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'mgba'
```

**Comment by Jourdelune** [comment]
Finnaly, I have moved `/home/pi/build/python/lib.linux-aarch64-3.7/mgba` to `/usr/local/lib/python3.7/dist-packages`.
I have try: this script:
```from mgba import core,image
c=core.load_path('/home/pi/T�l�chargements/PkmEmeraude.gba')
i=image.Image(*c.desired_video_dimensions())
c.set_video_buffer(i)
c.reset()
for x in range(800): c.run_frame()
with open("out.png", "w") as f: i.save_png(f)````

But I haven an error: `TypeError: write() argument must be str, not _cffi_backend.buffer`

**Comment by Jourdelune** [comment]
finnaly, I have move `/home/pi/build/python/lib.linux-aarch64-3.7/` to the place where the python modules are installed and it works.
There are only 2 questions left, how can I press a button and save the game?

**Comment by Jourdelune** [comment]
I have found on the coode of lib. Thanks^^
