### ISSUE TITLE
Segfault when loading cheat file

### ISSUE THREAD

**Issue by AlfredoRamos** [mgba-emu/mgba#242]
As title says, I get a segmentation fault when trying to load a cheat file.

It happened 4 times of 5 tries, only once it exited "normally".

**segfault**
```
$ gdb -ex run mgba-qt
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from mgba-qt...(no debugging symbols found)...done.
Starting program: /usr/bin/mgba-qt 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffdff16700 (LWP 20201)]
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
[New Thread 0x7fffdc9bc700 (LWP 20202)]
[New Thread 0x7fffd56df700 (LWP 20203)]
[New Thread 0x7fffd4df3700 (LWP 20205)]
[Thread 0x7fffd4df3700 (LWP 20205) exited]
Cheats: CodeBreaker encryption not supported
Cheats: CodeBreaker code 5EFBDA0A D385 not supported

Thread 1 "mgba-qt" received signal SIGSEGV, Segmentation fault.
0x00007ffff780ac2c in GBASetBreakpoint () from /usr/lib/libmgba.so.0.5
(gdb) bt full
#0  0x00007ffff780ac2c in GBASetBreakpoint () from /usr/lib/libmgba.so.0.5
No symbol table info available.
#1  0x00007ffff780ae41 in GBACheatAddSet () from /usr/lib/libmgba.so.0.5
No symbol table info available.
#2  0x00007ffff780b0d3 in GBACheatParseFile () from /usr/lib/libmgba.so.0.5
No symbol table info available.
#3  0x000000000044b506 in QGBA::CheatsModel::loadFile(QString const&) ()
No symbol table info available.
#4  0x0000000000450964 in QGBA::CheatsView::load() ()
No symbol table info available.
#5  0x00007ffff699c10a in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/libQt5Core.so.5
No symbol table info available.
#6  0x00007ffff75facb2 in QAbstractButton::clicked(bool) ()
   from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#7  0x00007ffff735d114 in ?? () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#8  0x00007ffff735e729 in ?? () from /usr/lib/libQt5Widgets.so.5
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#9  0x00007ffff735e8a4 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#10 0x00007ffff72a2fd8 in QWidget::event(QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#11 0x00007ffff725ffcc in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#12 0x00007ffff7265ba9 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#13 0x00007ffff696d9ab in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /usr/lib/libQt5Core.so.5
No symbol table info available.
#14 0x00007ffff7264ab2 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
   from /usr/lib/libQt5Widgets.so.5
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#15 0x00007ffff72bd54b in ?? () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#16 0x00007ffff72bfb0b in ?? () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#17 0x00007ffff725ffcc in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#18 0x00007ffff72654a6 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#19 0x00007ffff696d9ab in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /usr/lib/libQt5Core.so.5
No symbol table info available.
#20 0x00007ffff6cae231 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
No symbol table info available.
#21 0x00007ffff6cafef5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#22 0x00007ffff6c95318 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
No symbol table info available.
#23 0x00007fffe128a5f0 in ?? () from /usr/lib/libQt5XcbQpa.so.5
No symbol table info available.
#24 0x00007ffff1aa1d87 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#25 0x00007ffff1aa1fe0 in ?? () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#26 0x00007ffff1aa208c in g_main_context_iteration ()
   from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#27 0x00007ffff69c433f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#28 0x00007ffff696b37a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)
    () from /usr/lib/libQt5Core.so.5
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#29 0x00007ffff697333c in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#30 0x000000000044841a in main ()
No symbol table info available.
(gdb) quit
```

**exited "normally"** (the app closes itself)
- https://pastebin.osuosl.org/38611/raw/

Arch Linux x64, Qt 5.5.1, mgba-qt 0.5-1-91fa32c-dirty

**Comment by endrift** [comment]
Was a game loaded when you tried to load the cheats?

**Comment by AlfredoRamos** [comment]
Yes, I was in-game.

**Comment by endrift** [comment]
Can you attach the cheat file used?
