### ISSUE TITLE
segfault when loading a ROM

### ISSUE THREAD

**Issue by bendem** [mgba-emu/mgba#302]
Using fedora 24 (x86_64) / i3wm and current master (d3763b0f5de78ba2f18509dd5cad1b02af9c8ef5).

```
(gdb) thread apply all bt

Thread 9 (Thread 0x7fffc6984700 (LWP 23335)):
#0  0x00007ffff7f8bc8c in qgl1_functions() () at /lib64/libQt5OpenGL.so.5
#1  0x00007ffff7f8e835 in QGLContextPrivate::maxTextureSize() () at /lib64/libQt5OpenGL.so.5
#2  0x00007ffff7fad54f in QGL2PaintEngineEx::drawPixmap(QRectF const&, QPixmap const&, QRectF const&) () at /lib64/libQt5OpenGL.so.5
#3  0x00007ffff4369da8 in QPaintEngineEx::drawPixmap(QPointF const&, QPixmap const&) () at /lib64/libQt5Gui.so.5
#4  0x00007ffff43964db in QPainter::drawPixmap(QPointF const&, QPixmap const&) () at /lib64/libQt5Gui.so.5
#5  0x0000000000489139 in QGBA::MessagePainter::paint(QPainter*) ()
#6  0x000000000045bde8 in QGBA::PainterGL::draw() ()
#7  0x00007ffff3e92bd9 in QObject::event(QEvent*) () at /lib64/libQt5Core.so.5
#8  0x00007ffff46fcc0c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#9  0x00007ffff47020ef in QApplication::notify(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#10 0x00007ffff3e697aa in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#11 0x00007ffff3e6b84f in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib64/libQt5Core.so.5
#12 0x00007ffff3eb91b3 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib64/libQt5Core.so.5
#13 0x00007fffebf35703 in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#14 0x00007fffebf35ab0 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#15 0x00007fffebf35b5c in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#16 0x00007ffff3eb924b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#17 0x00007ffff3e685ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#18 0x00007ffff3cc7343 in QThread::exec() () at /lib64/libQt5Core.so.5
#19 0x00007ffff3ccb99a in QThreadPrivate::start(void*) () at /lib64/libQt5Core.so.5
#20 0x00007ffff2ba35ca in start_thread () at /lib64/libpthread.so.0
#21 0x00007ffff30beead in clone () at /lib64/libc.so.6

Thread 8 (Thread 0x7fffc7185700 (LWP 23334)):
#0  0x00007ffff30b33f1 in ppoll () at /lib64/libc.so.6
#1  0x00007fffd0bf120d in pa_mainloop_poll () at /lib64/libpulse.so.0
#2  0x00007fffd0bf17fe in pa_mainloop_iterate () at /lib64/libpulse.so.0
#3  0x00007ffff7b7c8d7 in PULSEAUDIO_WaitDevice () at /lib64/libSDL2-2.0.so.0
#4  0x00007ffff7ae4abf in SDL_RunAudio () at /lib64/libSDL2-2.0.so.0
#5  0x00007ffff7b4346c in SDL_RunThread () at /lib64/libSDL2-2.0.so.0
#6  0x00007ffff7b90f39 in RunThread () at /lib64/libSDL2-2.0.so.0
#7  0x00007ffff2ba35ca in start_thread () at /lib64/libpthread.so.0
#8  0x00007ffff30beead in clone () at /lib64/libc.so.6

Thread 7 (Thread 0x7fffc7986700 (LWP 23333)):
#0  0x00007ffff30b33f1 in ppoll () at /lib64/libc.so.6
#1  0x00007fffd0bf120d in pa_mainloop_poll () at /lib64/libpulse.so.0
#2  0x00007fffd0bf17fe in pa_mainloop_iterate () at /lib64/libpulse.so.0
#3  0x00007fffd0bf18b0 in pa_mainloop_run () at /lib64/libpulse.so.0
#4  0x00007ffff7b7c9cf in HotplugThread () at /lib64/libSDL2-2.0.so.0
#5  0x00007ffff7b4346c in SDL_RunThread () at /lib64/libSDL2-2.0.so.0
#6  0x00007ffff7b90f39 in RunThread () at /lib64/libSDL2-2.0.so.0
#7  0x00007ffff2ba35ca in start_thread () at /lib64/libpthread.so.0
#8  0x00007ffff30beead in clone () at /lib64/libc.so.6

Thread 6 (Thread 0x7fffd2822700 (LWP 23332)):
#0  0x00007ffff2ba8bd0 in pthread_cond_wait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
#1  0x00007ffff786025f in mCoreSyncProduceAudio () at /home/bendem/Projects/c/mgba/build/libmgba.so.0.5
#2  0x00007ffff785cb0d in GBAAudioProcessEvents () at /home/bendem/Projects/c/mgba/build/libmgba.so.0.5
#3  0x00007ffff78477c8 in GBAProcessEvents () at /home/bendem/Projects/c/mgba/build/libmgba.so.0.5
#4  0x00007ffff7810b0a in _mCoreThreadRun () at /home/bendem/Projects/c/mgba/build/libmgba.so.0.5
#5  0x00007ffff2ba35ca in start_thread () at /lib64/libpthread.so.0
#6  0x00007ffff30beead in clone () at /lib64/libc.so.6

Thread 4 (Thread 0x7fffd37dc700 (LWP 23330)):
#0  0x00007ffff30b332d in poll () at /lib64/libc.so.6
#1  0x00007fffebf35a46 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#2  0x00007fffebf35b5c in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#3  0x00007ffff3eb922f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#4  0x00007ffff3e685ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#5  0x00007ffff3cc7343 in QThread::exec() () at /lib64/libQt5Core.so.5
#6  0x00007ffff3ccb99a in QThreadPrivate::start(void*) () at /lib64/libQt5Core.so.5
#7  0x00007ffff2ba35ca in start_thread () at /lib64/libpthread.so.0
#8  0x00007ffff30beead in clone () at /lib64/libc.so.6

Thread 3 (Thread 0x7fffd9a74700 (LWP 23329)):
#0  0x00007ffff30b332d in poll () at /lib64/libc.so.6
#1  0x00007fffebf35a46 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#2  0x00007fffebf35b5c in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#3  0x00007ffff3eb922f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#4  0x00007ffff3e685ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#5  0x00007ffff3cc7343 in QThread::exec() () at /lib64/libQt5Core.so.5
#6  0x00007ffff7e12559 in QDBusConnectionManager::run() () at /lib64/libQt5DBus.so.5
#7  0x00007ffff3ccb99a in QThreadPrivate::start(void*) () at /lib64/libQt5Core.so.5
#8  0x00007ffff2ba35ca in start_thread () at /lib64/libpthread.so.0
#9  0x00007ffff30beead in clone () at /lib64/libc.so.6

Thread 2 (Thread 0x7fffdadb5700 (LWP 23328)):
#0  0x00007ffff30b332d in poll () at /lib64/libc.so.6
#1  0x00007fffef85af80 in _xcb_conn_wait () at /lib64/libxcb.so.1
#2  0x00007fffef85cb79 in xcb_wait_for_event () at /lib64/libxcb.so.1
#3  0x00007fffde993da9 in QXcbEventReader::run() () at /lib64/libQt5XcbQpa.so.5
#4  0x00007ffff3ccb99a in QThreadPrivate::start(void*) () at /lib64/libQt5Core.so.5
#5  0x00007ffff2ba35ca in start_thread () at /lib64/libpthread.so.0
#6  0x00007ffff30beead in clone () at /lib64/libc.so.6

Thread 1 (Thread 0x7ffff7eb6980 (LWP 23324)):
#0  0x00007ffff30b332d in poll () at /lib64/libc.so.6
#1  0x00007fffebf35a46 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#2  0x00007fffebf35b5c in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#3  0x00007ffff3eb922f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#4  0x00007ffff3e685ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#5  0x00007ffff3e7017c in QCoreApplication::exec() () at /lib64/libQt5Core.so.5
#6  0x0000000000446337 in main ()
(gdb) 
(gdb) 
(gdb) bt
#0  0x00007ffff7f8bc8c in qgl1_functions() () at /lib64/libQt5OpenGL.so.5
#1  0x00007ffff7f8e835 in QGLContextPrivate::maxTextureSize() () at /lib64/libQt5OpenGL.so.5
#2  0x00007ffff7fad54f in QGL2PaintEngineEx::drawPixmap(QRectF const&, QPixmap const&, QRectF const&) () at /lib64/libQt5OpenGL.so.5
#3  0x00007ffff4369da8 in QPaintEngineEx::drawPixmap(QPointF const&, QPixmap const&) () at /lib64/libQt5Gui.so.5
#4  0x00007ffff43964db in QPainter::drawPixmap(QPointF const&, QPixmap const&) () at /lib64/libQt5Gui.so.5
#5  0x0000000000489139 in QGBA::MessagePainter::paint(QPainter*) ()
#6  0x000000000045bde8 in QGBA::PainterGL::draw() ()
#7  0x00007ffff3e92bd9 in QObject::event(QEvent*) () at /lib64/libQt5Core.so.5
#8  0x00007ffff46fcc0c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#9  0x00007ffff47020ef in QApplication::notify(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#10 0x00007ffff3e697aa in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#11 0x00007ffff3e6b84f in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib64/libQt5Core.so.5
#12 0x00007ffff3eb91b3 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib64/libQt5Core.so.5
#13 0x00007fffebf35703 in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#14 0x00007fffebf35ab0 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#15 0x00007fffebf35b5c in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#16 0x00007ffff3eb924b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#17 0x00007ffff3e685ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#18 0x00007ffff3cc7343 in QThread::exec() () at /lib64/libQt5Core.so.5
#19 0x00007ffff3ccb99a in QThreadPrivate::start(void*) () at /lib64/libQt5Core.so.5
#20 0x00007ffff2ba35ca in start_thread () at /lib64/libpthread.so.0
#21 0x00007ffff30beead in clone () at /lib64/libc.so.6
```

**Comment by endrift** [comment]
Sounds like a bug in Qt. Try switching the Display driver to a different Qt type, and ensuring that OpenGL does in fact function on your computer.

**Comment by bendem** [comment]
> Try switching the Display driver to a different Qt type

I would love to if I had any idea what it meant or how to do it :innocent: 

> and ensuring that OpenGL does in fact function on your computer.

I've been writing OpenGL apps for a few months without trouble so I'm guessing it works. Also 
```
$ glxinfo64 | grep -i opengl.*version
OpenGL core profile version string: 4.3 (Core Profile) Mesa 12.0.1
OpenGL core profile shading language version string: 4.30
OpenGL version string: 3.0 Mesa 12.0.1
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 12.0.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
```

**Comment by endrift** [comment]
...it's a setting in mGBA. It's in the settings menu.

**Comment by bendem** [comment]
Indeed, setting it to software (Qt) fixed it. Should I try to report the problem upstream?

**Comment by endrift** [comment]
Did you try both OpenGL settings? Also like, good luck reporting it upstream without a repro case that works for others, especially if you're not on latest. :/

**Comment by bendem** [comment]
Yes, both OpenGL settings cause the crash. I see, guess this bug is not getting fixed then :S

**Comment by endrift** [comment]
Yeah sorry, that sounds like a Qt bug :/
