### ISSUE TITLE
Qt: Segfault on entering empty CLI debugger command

### ISSUE THREAD

**Issue by Anty-Lemon** [mgba-emu/mgba#693]
Build: 0.6-4446-69a30f95
OS: Debian 9.0 stretch amd64

Entering empty string as the first command to the CLI debugger triggers a segfault. Still occurs if the "Break" button is clicked first.

**Comment by Anty-Lemon** [comment]
Stack trace:
```
#0  0x00007ffff22ac974 in QString::toUtf8_helper(QString const&) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#1  0x000055555564d90d in QGBA::DebuggerConsoleController::historyLast(CLIDebuggerBackend*, unsigned long*) ()
#2  0x00007ffff78509ce in _commandLine ()
   from /home/<name>/src/mgba/build/libmgba.so.0.6
#3  0x00007ffff7844815 in _mCoreThreadRun ()
   from /home/<name>/src/mgba/build/libmgba.so.0.6
#4  0x00007ffff1322424 in start_thread (arg=0x7fffc935c700)
    at pthread_create.c:333
#5  0x00007ffff16209bf in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
```
