### ISSUE TITLE
Medusa Crashes if you close the emulator with keys binded to a controller not plugged in

### ISSUE THREAD

**Issue by JMC47** [mgba-emu/mgba#718]

**Comment by rootfather** [comment]
Confirmed.

Medusa also segfaults if you either connect or disconnect any (configured?) controller while medusa is running.

## plugging in a controller
```
(gdb) run
Starting program: C:\msys64\home\lserr\mgba\build\qt\medusa.exe
[New Thread 18396.0x3a08]
[New Thread 18396.0x1ca8]
[New Thread 18396.0x4778]
[New Thread 18396.0xfa0]
[New Thread 18396.0x45ac]
[New Thread 18396.0x3ac0]
[New Thread 18396.0x42dc]
[New Thread 18396.0x430]
[New Thread 18396.0x1e70]
[New Thread 18396.0x3784]
[New Thread 18396.0x3d34]
[New Thread 18396.0x2688]
[New Thread 18396.0x1bec]
[New Thread 18396.0x32cc]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x0000000000489e2b in mInputProfileLoad ()
(gdb) backtrace
#0  0x0000000000489e2b in mInputProfileLoad ()
#1  0x0000000000479069 in mSDLUpdateJoysticks ()
#2  0x00000000004341f3 in QGBA::InputController::updateJoysticks() ()
#3  0x000000000204bb44 in QMetaObject::activate(QObject*, int, int, void**) ()
   from C:\msys64\home\lserr\mgba\build\qt\Qt5Core.dll
#4  0x0000000002055853 in QTimer::timerEvent(QTimerEvent*) ()
   from C:\msys64\home\lserr\mgba\build\qt\Qt5Core.dll
#5  0x000000000204c8db in QObject::event(QEvent*) ()
   from C:\msys64\home\lserr\mgba\build\qt\Qt5Core.dll
#6  0x0000000001927f9c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from C:\msys64\home\lserr\mgba\build\qt\Qt5Widgets.dll
#7  0x000000000192eefc in QApplication::notify(QObject*, QEvent*) ()
   from C:\msys64\home\lserr\mgba\build\qt\Qt5Widgets.dll
#8  0x000000000202b812 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () from C:\msys64\home\lserr\mgba\build\qt\Qt5Core.dll
#9  0x0000000002071791 in QEventDispatcherWin32Private::sendTimerEvent(int) ()
   from C:\msys64\home\lserr\mgba\build\qt\Qt5Core.dll
#10 0x0000000002071b0f in QEventDispatcherWin32Private::sendTimerEvent(int) ()
   from C:\msys64\home\lserr\mgba\build\qt\Qt5Core.dll
#11 0x00007ffe4cf83b77 in WindowFromPoint ()
   from C:\WINDOWS\System32\user32.dll
#12 0x00007ffe4cf65896 in USER32!DispatchMessageW ()
   from C:\WINDOWS\System32\user32.dll
#13 0x00000000020711e3 in QEventDispatcherWin32::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from C:\msys64\home\lserr\mgba\build\qt\Qt5Core.dll
#14 0x000000006dd170d5 in qwindows!qt_plugin_instance ()
   from C:\msys64\mingw64\share\qt5\plugins\platforms\qwindows.dll
#15 0x000000000202abad in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from C:\msys64\home\lserr\mgba\build\qt\Qt5Core.dll
#16 0x0000000002031913 in QCoreApplication::exec() ()
   from C:\msys64\home\lserr\mgba\build\qt\Qt5Core.dll
#17 0x00000000005c81a7 in main ()
```

## unplugging a configured controller
```
(gdb) run
Starting program: C:\msys64\home\lserr\mgba\build\qt\medusa.exe
[New Thread 10528.0x38e4]
[New Thread 10528.0x35e0]
[New Thread 10528.0x433c]
[New Thread 10528.0x4204]
[New Thread 10528.0x1f84]
[New Thread 10528.0x3bc8]
[New Thread 10528.0x1e8c]
[New Thread 10528.0x2398]
[New Thread 10528.0x1f68]
[New Thread 10528.0x3c28]
[New Thread 10528.0x4090]
[New Thread 10528.0x1de8]
[New Thread 10528.0x1d50]
[New Thread 10528.0x2344]
[New Thread 10528.0x144]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x0000000000489e48 in mInputProfileLoad ()
(gdb) backtrace
#0  0x0000000000489e48 in mInputProfileLoad ()
#1  0x0000000000433b83 in QGBA::InputController::loadProfile(unsigned int, QString const&) ()
#2  0x0000000000434253 in QGBA::InputController::updateJoysticks() ()
#3  0x0000000001c3bb44 in QMetaObject::activate(QObject*, int, int, void**) ()
   from C:\msys64\home\lserr\mgba\build\qt\Qt5Core.dll
#4  0x0000000001c45853 in QTimer::timerEvent(QTimerEvent*) ()
   from C:\msys64\home\lserr\mgba\build\qt\Qt5Core.dll
#5  0x0000000001c3c8db in QObject::event(QEvent*) ()
   from C:\msys64\home\lserr\mgba\build\qt\Qt5Core.dll
#6  0x0000000002307f9c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from C:\msys64\home\lserr\mgba\build\qt\Qt5Widgets.dll
#7  0x000000000230eefc in QApplication::notify(QObject*, QEvent*) ()
   from C:\msys64\home\lserr\mgba\build\qt\Qt5Widgets.dll
#8  0x0000000001c1b812 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () from C:\msys64\home\lserr\mgba\build\qt\Qt5Core.dll
#9  0x0000000001c61791 in QEventDispatcherWin32Private::sendTimerEvent(int) ()
   from C:\msys64\home\lserr\mgba\build\qt\Qt5Core.dll
#10 0x0000000001c61b0f in QEventDispatcherWin32Private::sendTimerEvent(int) ()
   from C:\msys64\home\lserr\mgba\build\qt\Qt5Core.dll
#11 0x00007ffe4cf83b77 in WindowFromPoint ()
   from C:\WINDOWS\System32\user32.dll
#12 0x00007ffe4cf65896 in USER32!DispatchMessageW ()
   from C:\WINDOWS\System32\user32.dll
#13 0x0000000001c611e3 in QEventDispatcherWin32::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from C:\msys64\home\lserr\mgba\build\qt\Qt5Core.dll
#14 0x000000006dd170d5 in qwindows!qt_plugin_instance ()
   from C:\msys64\mingw64\share\qt5\plugins\platforms\qwindows.dll
#15 0x0000000001c1abad in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from C:\msys64\home\lserr\mgba\build\qt\Qt5Core.dll
#16 0x0000000001c21913 in QCoreApplication::exec() ()
   from C:\msys64\home\lserr\mgba\build\qt\Qt5Core.dll
#17 0x00000000005c81a7 in main ()

```

**Comment by yuriks** [comment]
I can still reproduce a crash as of 5f05662242ed37f20626e20b5b690a8cd1b7bd07 when a controller is plugged in or if you start medusa with a controlled plugged, but the stack traces are different:

```
Thread 1 received signal SIGSEGV, Segmentation fault.
QGBA::InputController::rebindKey (this=this@entry=0x96384c0, key=...)
    at C:/Users/yuriks/projects/mgba/src/platform/qt/input/InputController.cpp:850
850             bindKey(KEYBOARD, item->shortcut(), key);
(gdb) bt
#0  QGBA::InputController::rebindKey (this=this@entry=0x96384c0, key=...)
    at C:/Users/yuriks/projects/mgba/src/platform/qt/input/InputController.cpp:850
#1  0x0000000000460937 in QGBA::InputController::rebuildKeyIndex (
    this=this@entry=0x96384c0, index=index@entry=0x19213b18)
    at C:/Users/yuriks/projects/mgba/src/platform/qt/input/InputController.cpp:161
#2  0x0000000000469797 in QGBA::InputProfile::apply (this=0x19213af0,
    controller=controller@entry=0x96384c0)
    at C:/Users/yuriks/projects/mgba/src/platform/qt/input/InputProfile.cpp:93
#3  0x0000000000460c14 in QGBA::InputController::loadProfile (
    this=this@entry=0x96384c0, type=type@entry=1396984898, profile=...)
    at C:/Users/yuriks/projects/mgba/src/platform/qt/input/InputController.cpp:199
#4  0x0000000000460d14 in QGBA::InputController::updateJoysticks (
    this=0x96384c0)
    at C:/Users/yuriks/projects/mgba/src/platform/qt/input/InputController.cpp:372
#5  0x00000000034fa21d in QMetaObject::activate(QObject*, int, int, void**) ()
   from C:\msys64\mingw64\bin\Qt5Core.dll
#6  0x00000000035052fa in QTimer::timerEvent(QTimerEvent*) ()
   from C:\msys64\mingw64\bin\Qt5Core.dll
#7  0x00000000034fae2b in QObject::event(QEvent*) ()
   from C:\msys64\mingw64\bin\Qt5Core.dll
#8  0x0000000003d47b5c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from C:\msys64\mingw64\bin\Qt5Widgets.dll
#9  0x0000000003d4edd0 in QApplication::notify(QObject*, QEvent*) ()
   from C:\msys64\mingw64\bin\Qt5Widgets.dll
#10 0x00000000034cf488 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () from C:\msys64\mingw64\bin\Qt5Core.dll
#11 0x0000000003525c59 in QEventDispatcherWin32Private::sendTimerEvent(int) ()
   from C:\msys64\mingw64\bin\Qt5Core.dll
#12 0x0000000003526123 in QEventDispatcherWin32Private::sendTimerEvent(int) ()
   from C:\msys64\mingw64\bin\Qt5Core.dll
#13 0x00007ffd850cbc50 in USER32!CallWindowProcW ()
   from C:\WINDOWS\System32\user32.dll
#14 0x00007ffd850cb5cf in USER32!DispatchMessageW ()
   from C:\WINDOWS\System32\user32.dll
#15 0x00000000035254db in QEventDispatcherWin32::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from C:\msys64\mingw64\bin\Qt5Core.dll
#16 0x000000006dd1ad65 in qwindows!qt_plugin_instance ()
   from C:\msys64\mingw64\share\qt5\plugins\platforms\qwindows.dll
#17 0x00000000034cdb6f in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from C:\msys64\mingw64\bin\Qt5Core.dll
#18 0x00000000034d64c7 in QCoreApplication::exec() ()
   from C:\msys64\mingw64\bin\Qt5Core.dll
#19 0x00000000004d8a30 in main (argc=<optimized out>, argv=<optimized out>)
    at C:/Users/yuriks/projects/mgba/src/platform/qt/main.cpp:88
(gdb) p item
$1 = <optimized out>
```

**Comment by JMC47** [comment]
This can be closed, but the other controller issues still exist and there are new ones.
