### ISSUE TITLE
mGBA sometimes crashes when loading a second ROM in a session

### ISSUE THREAD

**Issue by yuriks** [mgba-emu/mgba#801]
This seems to have been introduced in e1325b03735fb0fcec8539485cc42a6322c05403.

Although the crash site seems to be random, the most common stack trace is:

```
Thread 22 "SDLAudioDev2" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 18896.0x55c8]
0x00007ffd8576bbdf in ntdll!RtlInitializeCriticalSectionEx ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
(gdb) bt
#0  0x00007ffd8576bbdf in ntdll!RtlInitializeCriticalSectionEx ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x00007ffd85744571 in ntdll!RtlEnterCriticalSection ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#2  0x00007ffd85744490 in ntdll!RtlEnterCriticalSection ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#3  0x000000007020ab53 in MutexLock (mutex=0x18bfddf0)
    at C:/Users/yuriks/projects/mgba/include/mgba-util/platform/windows/threading.h:31
#4  mCoreSyncLockAudio (sync=0x18bfdda0)
    at C:/Users/yuriks/projects/mgba/src/core/sync.c:96
#5  0x0000000000474263 in _mSDLAudioCallback (context=0x915d440,
    data=0xdd96090 "", len=6144)
    at C:/Users/yuriks/projects/mgba/src/platform/sdl/sdl-audio.c:108
#6  0x000000006c74383e in ?? () from C:\msys64\mingw64\bin\SDL2.dll
#7  0x000000006c7ae507 in ?? () from C:\msys64\mingw64\bin\SDL2.dll
#8  0x000000006c7f934a in ?? () from C:\msys64\mingw64\bin\SDL2.dll
#9  0x00007ffd82ccae06 in msvcrt!_beginthreadex ()
   from C:\WINDOWS\System32\msvcrt.dll
#10 0x00007ffd82ccaedc in msvcrt!_endthreadex ()
   from C:\WINDOWS\System32\msvcrt.dll
#11 0x00007ffd85632774 in KERNEL32!BaseThreadInitThunk ()
   from C:\WINDOWS\System32\kernel32.dll
#12 0x00007ffd857a0d51 in ntdll!RtlUserThreadStart ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#13 0x0000000000000000 in ?? ()
```

**Comment by endrift** [comment]
I think the GameController split should have fixed this. Please test on latest.

**Comment by yuriks** [comment]
Yep, can't reproduce anymore.
